export const DEFINED_APPLICATION_ROLES = Object.freeze({
  ROLE_ADMIN: "admin",
  ROLE_EDITOR: "editor",
  ROLE_VIEWER: "viewer",
});

export const DEFINED_RESOURCE_ACTIONS = Object.freeze({
  ACTION_CREATE: "create",
  ACTION_READ: "read",
  ACTION_UPDATE: "update",
  ACTION_DELETE: "delete",
});

export const ROLE_TO_PERMITTED_ACTIONS_MAP = Object.freeze({
  [DEFINED_APPLICATION_ROLES.ROLE_ADMIN]: [
    DEFINED_RESOURCE_ACTIONS.ACTION_CREATE,
    DEFINED_RESOURCE_ACTIONS.ACTION_READ,
    DEFINED_RESOURCE_ACTIONS.ACTION_UPDATE,
    DEFINED_RESOURCE_ACTIONS.ACTION_DELETE,
  ],
  [DEFINED_APPLICATION_ROLES.ROLE_EDITOR]: [
    DEFINED_RESOURCE_ACTIONS.ACTION_CREATE,
    DEFINED_RESOURCE_ACTIONS.ACTION_READ,
    DEFINED_RESOURCE_ACTIONS.ACTION_UPDATE,
  ],
  [DEFINED_APPLICATION_ROLES.ROLE_VIEWER]: [
    DEFINED_RESOURCE_ACTIONS.ACTION_READ,
  ],
});
